# Generated by Django 5.1.6 on 2025-08-25 17:58

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_brokerprofile_ownerprofile_staffprofile_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(default='System Administrator', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_email', models.EmailField(blank=True, help_text='Administrative email if different from account email', max_length=254, null=True)),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('admin_level', models.CharField(choices=[('system', 'System Administrator'), ('platform', 'Platform Administrator'), ('super', 'Super Administrator'), ('security', 'Security Administrator'), ('database', 'Database Administrator')], default='system', max_length=20)),
                ('system_access_level', models.CharField(choices=[('full', 'Full System Access'), ('restricted', 'Restricted Access'), ('read_only', 'Read-Only Access'), ('emergency', 'Emergency Access Only')], default='full', max_length=20)),
                ('departments_managed', models.JSONField(default=list, help_text='Departments under administration')),
                ('buildings_managed', models.JSONField(default=list, help_text='Buildings under administration')),
                ('user_groups_managed', models.JSONField(default=list, help_text='User groups under administration')),
                ('can_create_users', models.BooleanField(default=True)),
                ('can_modify_system_settings', models.BooleanField(default=True)),
                ('can_access_logs', models.BooleanField(default=True)),
                ('can_manage_backups', models.BooleanField(default=True)),
                ('can_manage_integrations', models.BooleanField(default=False)),
                ('can_view_financial_data', models.BooleanField(default=False)),
                ('can_manage_notifications', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('security_clearance_level', models.CharField(choices=[('standard', 'Standard'), ('elevated', 'Elevated'), ('high', 'High Security'), ('maximum', 'Maximum Security')], default='standard', max_length=20)),
                ('last_login_tracked', models.DateTimeField(blank=True, null=True)),
                ('login_attempts_today', models.PositiveIntegerField(default=0)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text/SMS'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], default='email', max_length=20)),
                ('availability_hours', models.CharField(blank=True, help_text="e.g., '24/7 On-Call' or 'Mon-Fri 9AM-6PM'", max_length=100, null=True)),
                ('on_call_schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('escalation_contact', models.CharField(blank=True, help_text='Who to contact if unreachable', max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('backup_admin_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('backup_admin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='Professional background and expertise', null=True)),
                ('technical_skills', models.JSONField(default=list, help_text='Technical skills and expertise')),
                ('certifications', models.JSONField(default=list, help_text='Professional certifications')),
                ('specializations', models.JSONField(default=list, help_text='Areas of specialization')),
                ('primary_work_location', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_work_setup', models.BooleanField(default=True)),
                ('vpn_access_required', models.BooleanField(default=True)),
                ('responsibilities', models.TextField(help_text='Primary administrative responsibilities')),
                ('system_knowledge', models.TextField(blank=True, help_text='Key systems and knowledge areas', null=True)),
                ('critical_contacts', models.TextField(blank=True, help_text='Critical vendor/partner contacts', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional administrative notes', null=True)),
                ('security_clearance_expiry', models.DateField(blank=True, null=True)),
                ('last_security_review', models.DateField(blank=True, null=True)),
                ('compliance_training_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='admin_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='users.adminprofile'),
        ),
    ]
