# Generated by Django 5.1.6 on 2025-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_adminprofile_profilephoto_admin_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='admin_level',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='availability_hours',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='backup_admin_contact',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='backup_admin_phone',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='buildings_managed',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_access_logs',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_create_users',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_manage_backups',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_manage_integrations',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_manage_notifications',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_modify_system_settings',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='can_view_financial_data',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='compliance_training_date',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='critical_contacts',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='departments_managed',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='escalation_contact',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='last_login_tracked',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='last_password_change',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='last_security_review',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='login_attempts_today',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='on_call_schedule',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='primary_work_location',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='remote_work_setup',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='security_clearance_expiry',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='security_clearance_level',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='system_access_level',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='system_knowledge',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='user_groups_managed',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='vpn_access_required',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email if different from account email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='buildings_managed',
            field=models.JSONField(default=list, help_text='Buildings under management'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_access_logs',
            field=models.BooleanField(default=False, help_text='Can view system logs and audit trails'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_create_users',
            field=models.BooleanField(default=False, help_text='Can create and manage user accounts'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_backups',
            field=models.BooleanField(default=False, help_text='Can manage system backups'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_integrations',
            field=models.BooleanField(default=False, help_text='Can manage third-party integrations'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_manage_notifications',
            field=models.BooleanField(default=False, help_text='Can manage system notifications'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_modify_system_settings',
            field=models.BooleanField(default=False, help_text='Can modify system configurations'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='can_view_financial_data',
            field=models.BooleanField(default=False, help_text='Can access financial reports and data'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='departments_managed',
            field=models.JSONField(default=list, help_text='Departments under management'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='security_clearance_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('elevated', 'Elevated'), ('high', 'High Security'), ('confidential', 'Confidential')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user_groups_managed',
            field=models.JSONField(default=list, help_text='User groups under management'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
