# Generated by Django 5.1.6 on 2025-08-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_simplify_admin_enhance_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='title',
        ),
    ]
