# Generated by Django 5.1.6 on 2025-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Job title or position', max_length=100),
        ),
    ]
