# Generated by Django 5.1.6 on 2025-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_position_to_admin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
