# Generated by Django 5.1.6 on 2025-11-14 20:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_adminprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{10,15}$')])),
                ('phone_verified', models.BooleanField(default=False, help_text='Has the phone number been verified via OTP')),
                ('phone_verified_at', models.DateTimeField(blank=True, help_text='When the phone was last verified', null=True)),
                ('sms_enabled', models.BooleanField(default=False, help_text='User has opted in to receive SMS')),
                ('sms_frequency', models.CharField(choices=[('all', 'All notifications'), ('important', 'Important only'), ('urgent', 'Urgent only'), ('none', 'No SMS notifications')], default='important', max_length=20)),
                ('tcpa_consent', models.BooleanField(default=False, help_text='User has given TCPA consent for automated texts')),
                ('tcpa_consent_date', models.DateTimeField(blank=True, help_text='When TCPA consent was given', null=True)),
                ('tcpa_consent_ip', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('notification_types', models.JSONField(default=list, help_text='Types of notifications user wants via SMS')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text="Don't send SMS during quiet hours")),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Start of quiet hours (user's timezone)", null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text="End of quiet hours (user's timezone)", null=True)),
                ('timezone', models.CharField(default='America/New_York', help_text="User's timezone for quiet hours", max_length=50)),
                ('opted_out', models.BooleanField(default=False, help_text='User has opted out via STOP command')),
                ('opted_out_date', models.DateTimeField(blank=True, null=True)),
                ('total_sms_sent', models.PositiveIntegerField(default=0, help_text='Total SMS messages sent to this number')),
                ('last_sms_sent', models.DateTimeField(blank=True, help_text='When the last SMS was sent', null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Number of failed SMS delivery attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Preferences',
                'verbose_name_plural': 'SMS Preferences',
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('verification', 'Verification Code'), ('2fa', 'Two-Factor Auth'), ('notification', 'Notification'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('marketing', 'Marketing')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='pending', max_length=20)),
                ('sms_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('segments', models.PositiveIntegerField(default=1, help_text='Number of SMS segments')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost in USD', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, help_text="Related object type (e.g., 'application', 'appointment')", max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Related object ID', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='users_smsme_phone_n_902bc8_idx'), models.Index(fields=['user', '-created_at'], name='users_smsme_user_id_704c66_idx'), models.Index(fields=['status', '-created_at'], name='users_smsme_status_133eaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Code Sent'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('expired', 'Code Expired'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('purpose', models.CharField(help_text='Purpose of verification (registration, 2fa, etc)', max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('sms_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='users_smsve_phone_n_d364e7_idx'), models.Index(fields=['user', '-created_at'], name='users_smsve_user_id_a20d29_idx')],
            },
        ),
    ]
