# Generated by Django 5.1.6 on 2025-11-27 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerprofile',
            name='commission_split',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Broker/Agent split percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Commission split cannot be negative'), django.core.validators.MaxValueValidator(100, message='Commission split cannot exceed 100%')]),
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='standard_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard commission percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Commission rate cannot be negative'), django.core.validators.MaxValueValidator(100, message='Commission rate cannot exceed 100%')]),
        ),
    ]
