# Generated by Django 5.1.6 on 2025-11-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_brokerprofile_commission_split_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['department', '_last_name'], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(blank=True, db_column='first_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='adminprofile',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='adminprofile',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_column='phone_number', max_length=20),
        ),
        migrations.RenameField(
            model_name='adminprofile',
            old_name='phone_number',
            new_name='_phone_number',
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='brokerprofile',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='brokerprofile',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.AlterField(
            model_name='brokerprofile',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20),
        ),
        migrations.RenameField(
            model_name='brokerprofile',
            old_name='phone_number',
            new_name='_phone_number',
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='first_name',
            field=models.CharField(db_column='first_name', help_text='First name or company representative', max_length=100),
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='last_name',
            field=models.CharField(db_column='last_name', help_text='Last name or company name if business', max_length=100),
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='primary_phone',
            field=models.CharField(db_column='primary_phone', max_length=20),
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='primary_phone',
            new_name='_primary_phone',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=100),
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
