# Generated by Django 5.1.6 on 2026-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_populate_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='sms_sid',
            field=models.CharField(blank=True, help_text='SMS provider message ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='smsverificationlog',
            name='sms_sid',
            field=models.CharField(blank=True, help_text='SMS provider message ID', max_length=100),
        ),
    ]
