# Generated by Django 5.1.6 on 2025-03-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='other_info',
        ),
    ]
