# Generated by Django 5.1.6 on 2025-07-30 07:37

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_application_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfodata',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
