# Generated by Django 5.1.6 on 2025-07-30 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('applications', '0007_alter_personalinfodata_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='manual_building_address',
            field=models.CharField(blank=True, help_text='Full building address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='manual_building_name',
            field=models.CharField(blank=True, help_text='Building name if not in our database', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='manual_unit_number',
            field=models.CharField(blank=True, help_text='Apartment/unit number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apartments.apartment'),
        ),
    ]
