# Generated by Django 5.1.6 on 2025-07-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_remove_applicant_current_landlord_contact'),
        ('applications', '0008_add_manual_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicant'),
        ),
    ]
