# Generated by Django 5.1.6 on 2025-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_personalinfodata_address_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfodata',
            name='broker_notes',
            field=models.TextField(blank=True, help_text='Notes about broker pre-filled information', null=True),
        ),
    ]
