# Generated by Django 5.1.6 on 2025-07-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_personalinfodata_broker_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
