# Generated by Django 5.1.6 on 2025-09-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_uploadedfile_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('own', 'Own')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='landlord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='landlord_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='length_at_address',
            field=models.CharField(blank=True, help_text='How long did you live here?', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='address',
            field=models.CharField(blank=True, help_text='Legacy field - use street_address_1 instead', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='apt_unit',
            field=models.CharField(blank=True, help_text='Legacy field - use street_address_2 instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='duration',
            field=models.CharField(blank=True, help_text='Legacy field - use length_at_address instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='landlord_contact',
            field=models.CharField(blank=True, help_text='Legacy field - use landlord_phone instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
