# Generated by Django 5.1.6 on 2026-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_is_revoked_application_revocation_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalemployment',
            old_name='is_current',
            new_name='currently_employed',
        ),
        migrations.RenameField(
            model_name='assetinfo',
            old_name='value',
            new_name='account_balance',
        ),
        migrations.RemoveField(
            model_name='additionalemployment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='additionalincome',
            name='amount',
        ),
        migrations.AddField(
            model_name='additionalemployment',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalemployment',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionalemployment',
            name='job_type',
            field=models.CharField(default='employed', max_length=20),
        ),
        migrations.AddField(
            model_name='additionalemployment',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='additionalemployment',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalemployment',
            name='supervisor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='additionalincome',
            name='average_annual_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalincome',
            name='income_source',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='asset_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomedata',
            name='bank_statement_1',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/bank_statements/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='bank_statement_2',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/bank_statements/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='id_back_image',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/id_images/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='id_front_image',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/id_images/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='id_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='paystub_1',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/paystubs/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='paystub_2',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/paystubs/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='paystub_3',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/paystubs/'),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='school_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='school_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='year_of_graduation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='bankruptcy_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='conviction_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='current_address_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='current_address_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='current_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='current_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='current_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalemployment',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='additionalincome',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalincome',
            name='source_type',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='asset_type',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='supervisor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
