# Generated by Django 5.1.6 on 2026-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_rename_is_current_additionalemployment_currently_employed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
