# Generated by Django 5.1.6 on 2026-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_application_payment_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomedata',
            old_name='company_name',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='incomedata',
            old_name='position',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='personalinfodata',
            old_name='current_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='personalinfodata',
            old_name='current_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='personalinfodata',
            old_name='current_address',
            new_name='street_address_1',
        ),
        migrations.RenameField(
            model_name='personalinfodata',
            old_name='apt_unit_number',
            new_name='street_address_2',
        ),
        migrations.RenameField(
            model_name='personalinfodata',
            old_name='current_zip',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='incomedata',
            name='additional_income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='additional_income_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='employment_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='proof_of_income',
            field=models.FileField(blank=True, null=True, upload_to='application_docs/proof/'),
        ),
    ]
