# Generated by Django 5.1.6 on 2026-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_rename_company_name_incomedata_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfodata',
            name='current_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='housing_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='reason_for_moving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
