# Generated by Django 5.1.6 on 2026-01-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_personalinfodata_current_monthly_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfodata',
            name='about_yourself',
        ),
        migrations.RemoveField(
            model_name='personalinfodata',
            name='address_duration',
        ),
        migrations.RemoveField(
            model_name='personalinfodata',
            name='broker_notes',
        ),
        migrations.RemoveField(
            model_name='personalinfodata',
            name='can_receive_sms',
        ),
        migrations.RemoveField(
            model_name='personalinfodata',
            name='leasing_agent',
        ),
    ]
