# Generated by Django 5.1.6 on 2026-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_remove_personalinfodata_about_yourself_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousaddress',
            name='months',
            field=models.IntegerField(blank=True, help_text='Months at this address', null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='years',
            field=models.IntegerField(blank=True, help_text='Years at this address', null=True),
        ),
    ]
