# Generated by Django 5.1.6 on 2026-01-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_previousaddress_months_previousaddress_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousaddress',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
