# Generated by Django 5.1.6 on 2026-01-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_pet_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedata',
            name='currently_employed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='has_additional_income',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='has_assets',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='has_multiple_jobs',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfodata',
            name='has_criminal_conviction',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfodata',
            name='has_filed_bankruptcy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfodata',
            name='has_pets',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfodata',
            name='is_rental_property',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
