# Generated by Django 5.1.6 on 2026-04-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_alter_incomedata_currently_employed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_docs/supporting/')),
                ('label', models.CharField(blank=True, help_text='Optional label for this document', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('income_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='applications.incomedata')),
            ],
        ),
    ]
