# Generated by Django 5.1.6 on 2026-04-03 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_add_supporting_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedata',
            name='id_back_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='id_front_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
