# Generated by Django 5.1.6 on 2026-04-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_change_id_images_to_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfodata',
            name='eviction_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfodata',
            name='has_been_evicted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
