# Generated by Django 5.1.6 on 2026-04-08 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_personalinfodata_eviction_explanation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Applicant's phone number (E.164)", max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('requested_fields', models.JSONField(default=list, help_text="List of dicts: [{'model': 'personal_info', 'field': 'employer', 'label': 'Employer Name'}, ...]")),
                ('collected_fields', models.JSONField(default=dict, help_text='Dict of field_name -> value that have been extracted and saved')),
                ('messages', models.JSONField(default=list, help_text="List of dicts: [{'role': 'assistant', 'content': '...'}, {'role': 'user', 'content': '...'}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Conversation expires after 24 hours')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_conversations', to='applications.application')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_sms_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
