# Generated by Django 5.1.6 on 2026-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_sms_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconversation',
            name='current_field_index',
            field=models.IntegerField(default=0, help_text="Index into requested_fields — which field we're currently asking about"),
        ),
    ]
