# Generated by Django 5.1.6 on 2025-03-06 21:37

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit_number', models.CharField(max_length=10)),
                ('bedrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('apartment_type', models.CharField(choices=[('multi_family', 'Multi-Family'), ('duplex', 'Duplex')], default='multi_family', max_length=20)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('deposit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('rented', 'Rented'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('lock_type', models.CharField(blank=True, max_length=50, null=True)),
                ('broker_fee_required', models.BooleanField(default=False)),
                ('paid_months', models.IntegerField(blank=True, null=True)),
                ('self_tour_status', models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=10, null=True)),
                ('lease_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('holding_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_stuff', models.CharField(blank=True, max_length=255, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.building')),
                ('amenities', models.ManyToManyField(blank=True, to='apartments.apartmentamenity')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_free', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('lease_terms', models.CharField(blank=True, max_length=50, null=True)),
                ('special_offer_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='apartments.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment')),
            ],
        ),
    ]
