# Generated by Django 5.1.6 on 2025-09-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='square_feet',
        ),
    ]
