# Generated by Django 5.1.6 on 2025-11-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='self_tour_status',
        ),
    ]
