# Generated by Django 5.1.6 on 2025-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_external_id_and_self_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
