# Generated by Django 5.1.6 on 2025-11-14 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_add_square_feet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of bathrooms', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of bedrooms (0 for studio)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='deposit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='holding_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Holding deposit to reserve unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='net_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net effective rent (after concessions)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, help_text='Gross rent (before concessions)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_feet',
            field=models.IntegerField(blank=True, help_text='Living space in square feet', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='apartmentconcession',
            name='months_free',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of free months offered', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
