# Generated by Django 5.1.6 on 2025-11-14 17:48

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_add_database_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lease_end', models.DateField(blank=True, help_text="When current tenant's lease ends", null=True)),
                ('available_date', models.DateField(help_text='Date unit becomes available for move-in')),
                ('notice_given_date', models.DateField(blank=True, help_text='Date current tenant gave notice', null=True)),
                ('turnover_days', models.IntegerField(default=7, help_text='Days needed for cleaning/repairs between tenants', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('is_reserved', models.BooleanField(default=False, help_text='Unit is reserved but not yet rented')),
                ('reserved_until', models.DateField(blank=True, help_text='Reservation expiry date', null=True)),
                ('reserved_by', models.CharField(blank=True, help_text='Name/ID of person holding reservation', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Availability Calendar',
                'ordering': ['available_date'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_plan_image', cloudinary.models.CloudinaryField(blank=True, help_text='Floor plan image file', max_length=255, null=True, verbose_name='floor_plan')),
                ('floor_plan_pdf_url', models.URLField(blank=True, help_text='Link to floor plan PDF', max_length=500, null=True)),
                ('title', models.CharField(default='Floor Plan', help_text="e.g., '2BR/2BA Layout A'", max_length=255)),
                ('total_square_feet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('living_area_sqft', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)])),
                ('bedroom_dimensions', models.JSONField(blank=True, help_text="JSON object with bedroom dimensions, e.g., {'master': '15x12', 'bedroom2': '11x10'}", null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary floor plan to show first')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_type', models.CharField(choices=[('garage', 'Garage'), ('covered', 'Covered Parking'), ('surface', 'Surface Lot'), ('street', 'Street Parking'), ('driveway', 'Driveway'), ('carport', 'Carport'), ('valet', 'Valet Parking'), ('none', 'No Parking')], max_length=20)),
                ('spaces_included', models.IntegerField(default=0, help_text='Number of spaces included with rent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('spaces_available', models.IntegerField(default=0, help_text='Additional spaces available for rent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rate per additional space', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location_description', models.CharField(blank=True, help_text="e.g., 'Basement level B2' or 'Adjacent lot'", max_length=255, null=True)),
                ('distance_from_unit', models.CharField(blank=True, help_text="e.g., 'Same building' or '100 feet'", max_length=100, null=True)),
                ('is_assigned', models.BooleanField(default=False, help_text='Specific spots assigned vs first-come')),
                ('has_ev_charging', models.BooleanField(default=False, help_text='Electric vehicle charging available')),
                ('ev_charging_cost', models.CharField(blank=True, help_text="e.g., '$30/month' or 'Included'", max_length=100, null=True)),
                ('access_type', models.CharField(blank=True, help_text="e.g., 'Key fob', 'Remote', 'Gate code'", max_length=100, null=True)),
                ('guest_parking_available', models.BooleanField(default=False)),
                ('guest_parking_details', models.TextField(blank=True, help_text='Guest parking rules and availability', null=True)),
                ('height_clearance', models.CharField(blank=True, help_text="e.g., '7 feet' for garages", max_length=50, null=True)),
                ('compact_only', models.BooleanField(default=False, help_text='Limited to compact cars')),
                ('notes', models.TextField(blank=True, null=True)),
                ('waitlist_available', models.BooleanField(default=False, help_text='Can join waitlist if no spaces available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Parking Options',
                'ordering': ['parking_type', 'monthly_rate'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_price', models.DecimalField(decimal_places=2, help_text='Monthly rent at this point in time', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_effective_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Net rent after concessions', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('concession_description', models.CharField(blank=True, help_text="e.g., '2 months free on 14-month lease'", max_length=255, null=True)),
                ('effective_date', models.DateField(help_text='Date this price became effective')),
                ('end_date', models.DateField(blank=True, help_text='Date this price ended (null if current)', null=True)),
                ('change_reason', models.CharField(blank=True, choices=[('market_adjustment', 'Market Adjustment'), ('renovation', 'Post-Renovation Increase'), ('seasonal', 'Seasonal Adjustment'), ('promotion', 'Promotional Pricing'), ('demand', 'Demand-Based Pricing'), ('new_listing', 'New Listing'), ('other', 'Other')], max_length=20, null=True)),
                ('change_notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Price History',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_included', models.BooleanField(default=False)),
                ('gas_included', models.BooleanField(default=False)),
                ('electricity_included', models.BooleanField(default=False)),
                ('heat_included', models.BooleanField(default=False)),
                ('hot_water_included', models.BooleanField(default=False)),
                ('trash_included', models.BooleanField(default=True)),
                ('sewer_included', models.BooleanField(default=True)),
                ('internet_included', models.BooleanField(default=False)),
                ('cable_included', models.BooleanField(default=False)),
                ('water_cost_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly water cost if not included', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('gas_cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('gas_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('internet_providers', models.TextField(blank=True, help_text='Available internet providers for the building', null=True)),
                ('utility_notes', models.TextField(blank=True, help_text='Additional information about utilities', null=True)),
                ('electricity_meter_type', models.CharField(blank=True, choices=[('individual', 'Individual Meters'), ('master', 'Master Metered'), ('submeter', 'Submetered'), ('rubs', 'RUBS (Ratio Utility Billing)')], max_length=20, null=True)),
                ('gas_meter_type', models.CharField(blank=True, choices=[('individual', 'Individual Meters'), ('master', 'Master Metered'), ('submeter', 'Submetered'), ('rubs', 'RUBS (Ratio Utility Billing)')], max_length=20, null=True)),
                ('water_meter_type', models.CharField(blank=True, choices=[('individual', 'Individual Meters'), ('master', 'Master Metered'), ('submeter', 'Submetered'), ('rubs', 'RUBS (Ratio Utility Billing)')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentVirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('matterport', 'Matterport 3D Tour'), ('video', 'Video Walkthrough'), ('360_photos', '360° Photos'), ('live_tour', 'Live Virtual Tour'), ('youtube', 'YouTube Video'), ('vimeo', 'Vimeo Video'), ('other', 'Other')], max_length=20)),
                ('tour_url', models.URLField(help_text='URL to virtual tour', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Display title for the tour', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration for video tours', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='apartment',
            name='apt_status_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='apartment',
            name='apt_beds_baths_idx',
        ),
        migrations.RemoveIndex(
            model_name='apartment',
            name='apt_building_status_idx',
        ),
        migrations.AddField(
            model_name='apartmentavailability',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_calendar', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentfloorplan',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentparking',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_options', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentpricehistory',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentutilities',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentvirtualtour',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tours', to='apartments.apartment'),
        ),
    ]
