# Generated by Django 5.1.6 on 2025-11-14 18:04

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_add_extended_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentSearchIndex',
            fields=[
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_index', serialize=False, to='apartments.apartment')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('building_name', models.CharField(max_length=255)),
                ('building_address', models.TextField()),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('full_text', models.TextField(help_text='All searchable text concatenated')),
                ('amenities_text', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Index',
                'verbose_name_plural': 'Search Indexes',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='apartments__search__56805e_gin'), models.Index(fields=['neighborhood'], name='apartments__neighbo_53e065_idx'), models.Index(fields=['latitude', 'longitude'], name='apartments__latitud_73efad_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Search term or phrase', max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=0, help_text='Number of times searched')),
                ('click_count', models.IntegerField(default=0, help_text='Number of clicks from search results')),
                ('last_searched', models.DateTimeField(blank=True, help_text='Last time this term was searched', null=True)),
                ('category', models.CharField(blank=True, choices=[('neighborhood', 'Neighborhood'), ('amenity', 'Amenity'), ('building', 'Building Name'), ('feature', 'Feature'), ('price', 'Price Range'), ('size', 'Size/Bedrooms'), ('other', 'Other')], max_length=50, null=True)),
                ('searches_this_week', models.IntegerField(default=0)),
                ('searches_this_month', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched'],
                'indexes': [models.Index(fields=['term'], name='apartments__term_b2bc0b_idx'), models.Index(fields=['-search_count'], name='apartments__search__a303e5_idx'), models.Index(fields=['-last_searched'], name='apartments__last_se_4e42f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApartmentSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=100, null=True)),
                ('search_params', models.JSONField(default=dict, help_text='Complete search parameters used')),
                ('search_text', models.TextField(blank=True, help_text='Free text search query', null=True)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('results_clicked', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='IDs of apartments clicked from results', size=None)),
                ('search_location', models.JSONField(blank=True, help_text='Location data if location-based search', null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('search_source', models.CharField(choices=[('homepage', 'Homepage'), ('listing', 'Listing Page'), ('saved', 'Saved Search'), ('alert', 'Email Alert'), ('api', 'API'), ('mobile', 'Mobile App'), ('other', 'Other')], default='listing', max_length=50)),
                ('search_duration_ms', models.IntegerField(blank=True, help_text='Time to execute search in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='apartments__user_id_e07e7f_idx'), models.Index(fields=['session_id', '-created_at'], name='apartments__session_619bc4_idx'), models.Index(fields=['-created_at'], name='apartments__created_940ecf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApartmentSearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to use for alerts')),
                ('is_default', models.BooleanField(default=False, help_text='Default search to load')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_bedrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_bedrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_square_feet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('max_square_feet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('neighborhoods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Preferred neighborhoods', size=None)),
                ('search_latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Center point latitude for distance search', max_digits=10, null=True)),
                ('search_longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Center point longitude for distance search', max_digits=11, null=True)),
                ('search_radius_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Search radius in miles', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50)])),
                ('search_address', models.CharField(blank=True, help_text='Address used for search center', max_length=255, null=True)),
                ('required_amenities', models.JSONField(blank=True, default=list, help_text='List of required amenity names')),
                ('apartment_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Preferred apartment types', size=None)),
                ('pets_allowed', models.BooleanField(blank=True, help_text='Must allow pets', null=True)),
                ('parking_required', models.BooleanField(blank=True, help_text='Must have parking', null=True)),
                ('utilities_included_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Required included utilities', size=None)),
                ('earliest_move_date', models.DateField(blank=True, help_text='Earliest possible move-in date', null=True)),
                ('latest_move_date', models.DateField(blank=True, help_text='Latest acceptable move-in date', null=True)),
                ('alert_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='never', max_length=20)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-last_used', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='apartments__user_id_4d695b_idx'), models.Index(fields=['user', 'is_default'], name='apartments__user_id_d3f948_idx')],
            },
        ),
    ]
