# Generated by Django 5.1.6 on 2026-01-02 13:24

from django.db import migrations

def populate_apartment_amenity_icons(apps, schema_editor):
    ApartmentAmenity = apps.get_model('apartments', 'ApartmentAmenity')
    
    # Mapping of apartment feature names to FontAwesome icon classes
    icon_mapping = {
        'Air Conditioning': 'fa-snowflake',
        'Central AC': 'fa-snowflake',
        'Balcony': 'fa-cloud-sun',
        'Balcony/Patio': 'fa-cloud-sun',
        'City Views': 'fa-city',
        'Dishwasher': 'fa-sink',
        'Exposed Brick': 'fa-border-all',
        'Fireplace': 'fa-fire',
        'Garden Access': 'fa-leaf',
        'Hardwood Floors': 'fa-layer-group',
        'High Ceilings': 'fa-arrows-up-down',
        'Microwave': 'fa-utensils',
        'Natural Light': 'fa-sun',
        'Parking Space': 'fa-square-parking',
        'Pet Friendly': 'fa-paw',
        'Refrigerator': 'fa-temperature-low',
        'Stainless Steel Appliances': 'fa-kitchen-set',
        'Storage Unit': 'fa-box',
        'Updated Bathroom': 'fa-bath',
        'Updated Kitchen': 'fa-fire-burner',
        'Walk-in Closet': 'fa-shirt',
        'Washer/Dryer': 'fa-soap',
        'Washer/Dryer In Unit': 'fa-soap',
        'In Unit': 'fa-soap',
    }

    count = 0
    for name, icon in icon_mapping.items():
        updated = ApartmentAmenity.objects.filter(name__iexact=name).update(icon=icon)
        count += updated
        
    print(f"\nUpdated {count} apartment amenities with icons.")

def reverse_apartment_amenity_icons(apps, schema_editor):
    ApartmentAmenity = apps.get_model('apartments', 'ApartmentAmenity')
    ApartmentAmenity.objects.all().update(icon='fa-check-circle')

class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_apartmentamenity_icon'),
    ]

    operations = [
        migrations.RunPython(populate_apartment_amenity_icons, reverse_apartment_amenity_icons),
    ]
