# Generated by Django 5.1.6 on 2025-03-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='current_landlord_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('own', 'Own')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='length_at_current_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
