# Generated by Django 5.1.6 on 2025-03-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_current_landlord_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='current_landlord_contact',
        ),
    ]
