# Generated by Django 5.1.6 on 2025-08-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('applicants', '0004_applicant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='placed_apartment',
            field=models.ForeignKey(blank=True, help_text='Apartment where applicant was placed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='placement_date',
            field=models.DateTimeField(blank=True, help_text='Date when applicant was placed in an apartment', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='placement_status',
            field=models.CharField(choices=[('unplaced', 'Unplaced'), ('placed', 'Placed'), ('withdrawn', 'Withdrawn')], default='unplaced', max_length=20),
        ),
    ]
