# Generated by Django 5.1.6 on 2025-09-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicant_city_alter_applicant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='current_landlord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
