# Generated by Django 5.1.6 on 2025-09-04 19:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_previousaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('state_id', 'State ID')], help_text='Type of identification document', max_length=20)),
                ('document_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_documents', to='applicants.applicant')),
            ],
            options={
                'ordering': ['id_type'],
                'unique_together': {('applicant', 'id_type')},
            },
        ),
    ]
