# Generated by Django 5.1.6 on 2025-09-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_add_identification_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='max_bathrooms',
            field=models.CharField(blank=True, help_text='Maximum bathrooms desired', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='max_bedrooms',
            field=models.CharField(blank=True, help_text='Maximum bedrooms desired', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='min_bathrooms',
            field=models.CharField(blank=True, help_text='Minimum bathrooms desired', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='min_bedrooms',
            field=models.CharField(blank=True, help_text='Minimum bedrooms desired', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number_of_bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number_of_bedrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True),
        ),
    ]
