# Generated by Django 5.1.6 on 2025-09-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_add_bedroom_bathroom_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, help_text="Pet's name", max_length=100, null=True),
        ),
    ]
