# Generated by Django 5.1.6 on 2025-09-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_add_pet_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_rank', models.PositiveIntegerField(help_text='1 = highest preference, higher numbers = lower preference')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.neighborhood')),
            ],
            options={
                'ordering': ['preference_rank'],
                'unique_together': {('applicant', 'neighborhood'), ('applicant', 'preference_rank')},
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='ranked_neighborhood_preferences',
            field=models.ManyToManyField(blank=True, related_name='ranked_applicants', through='applicants.NeighborhoodPreference', to='applicants.neighborhood'),
        ),
    ]
