# Generated by Django 5.1.6 on 2025-09-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('applicants', '0012_neighborhoodpreference_and_more'),
        ('buildings', '0002_add_brokers_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantApartmentAmenityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.IntegerField(choices=[(2, 'Nice to Have'), (3, 'Very Important'), (4, 'Must Have')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartmentamenity')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_amenity_preferences', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Apartment Amenity Preference',
                'verbose_name_plural': 'Apartment Amenity Preferences',
                'ordering': ['-priority_level', 'amenity__name'],
                'unique_together': {('applicant', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantBuildingAmenityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.IntegerField(choices=[(2, 'Nice to Have'), (3, 'Very Important'), (4, 'Must Have')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.amenity')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_amenity_preferences', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Building Amenity Preference',
                'verbose_name_plural': 'Building Amenity Preferences',
                'ordering': ['-priority_level', 'amenity__name'],
                'unique_together': {('applicant', 'amenity')},
            },
        ),
    ]
