# Generated by Django 5.1.6 on 2025-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0013_add_amenity_preference_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('student', 'I am a student'), ('employed', 'I am employed'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='year_of_graduation',
            field=models.CharField(blank=True, help_text='Expected graduation year (e.g., 2025)', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applicantapartmentamenitypreference',
            name='priority_level',
            field=models.IntegerField(choices=[(2, 'Nice to Have'), (3, 'Important'), (4, 'Must Have')]),
        ),
        migrations.AlterField(
            model_name='applicantbuildingamenitypreference',
            name='priority_level',
            field=models.IntegerField(choices=[(2, 'Nice to Have'), (3, 'Important'), (4, 'Must Have')]),
        ),
    ]
