# Generated by Django 5.1.6 on 2025-09-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_applicant_employment_status_applicant_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='currently_employed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='supervisor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='year_of_graduation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
