# Generated by Django 5.1.6 on 2025-09-05 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0015_applicant_annual_income_applicant_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset_type', models.CharField(choices=[('student', 'Student Asset'), ('employed', 'Employed Asset'), ('other', 'Other Asset')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='applicants.applicant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantIncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_source', models.CharField(max_length=255)),
                ('average_annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(choices=[('student', 'Student Income'), ('employed', 'Employed Income'), ('other', 'Other Income')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='applicants.applicant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supervisor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('currently_employed', models.BooleanField(default=True)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('student', 'Student Job'), ('employed', 'Additional Employment')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='applicants.applicant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
