# Generated by Django 5.1.6 on 2025-09-08 21:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0016_applicantasset_applicantincomesource_applicantjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identificationdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='identificationdocument',
            name='document_image_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='identificationdocument',
            name='document_image_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='identificationdocument',
            name='side',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('single', 'Single (Passport)')], default='single', help_text='Side of the document (front/back/single)', max_length=10),
        ),
        migrations.AlterField(
            model_name='identificationdocument',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driver_license', "Driver's License"), ('state_id', 'State ID')], help_text='Type of identification document', max_length=20),
        ),
    ]
