# Generated by Django 5.1.6 on 2025-09-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0017_alter_identificationdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='employer_contact_info',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='length_of_employment',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='applicantcrm',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm', to='applicants.applicant'),
        ),
    ]
