# Generated by Django 5.1.6 on 2025-09-09 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0018_remove_applicant_current_employer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_completed', 'Profile Completed'), ('password_changed', 'Password Changed'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('session_timeout', 'Session Timeout'), ('application_started', 'Application Started'), ('application_updated', 'Application Updated'), ('application_submitted', 'Application Submitted'), ('application_viewed', 'Application Viewed'), ('apartment_viewed', 'Apartment Viewed'), ('apartment_favorited', 'Apartment Favorited'), ('apartment_unfavorited', 'Apartment Unfavorited'), ('building_viewed', 'Building Viewed'), ('property_search', 'Property Search'), ('virtual_tour', 'Virtual Tour Viewed'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent'), ('phone_call', 'Phone Call'), ('message_received', 'Message Received'), ('message_replied', 'Message Replied'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('crm_note_added', 'CRM Note Added'), ('status_changed', 'Status Changed'), ('broker_assigned', 'Broker Assigned'), ('follow_up_scheduled', 'Follow-up Scheduled'), ('meeting_scheduled', 'Meeting Scheduled'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('form_started', 'Form Started'), ('form_abandoned', 'Form Abandoned')], max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='applicants.applicant')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this activity (broker, admin, or the applicant themselves)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant', '-created_at'], name='applicants__applica_ee7e6c_idx'), models.Index(fields=['activity_type'], name='applicants__activit_a3cb9a_idx'), models.Index(fields=['triggered_by'], name='applicants__trigger_aa3ad4_idx')],
            },
        ),
    ]
