# Generated by Django 5.1.6 on 2025-09-10 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0019_applicantactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='current_address_months',
            field=models.IntegerField(blank=True, help_text='Additional months at current address', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='applicant',
            name='current_address_years',
            field=models.IntegerField(blank=True, help_text='Years at current address', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
