# Generated by Django 5.1.6 on 2025-09-10 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0020_applicant_current_address_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='current_address_months',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='current_address_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='evicted_before',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
