# Generated by Django 5.1.6 on 2025-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0022_add_activity_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicantactivity',
            name='applicants_applica_c5f8d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicantactivity',
            name='applicants_activit_8b3e4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicantactivity',
            name='applicants_applica_7a2c1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicantactivity',
            name='applicants_created_9f5b2a_idx',
        ),
        migrations.AlterField(
            model_name='applicantactivity',
            name='activity_type',
            field=models.CharField(choices=[('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_completed', 'Profile Completed'), ('password_changed', 'Password Changed'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('session_timeout', 'Session Timeout'), ('application_started', 'Application Started'), ('application_updated', 'Application Updated'), ('application_submitted', 'Application Submitted'), ('application_viewed', 'Application Viewed'), ('apartment_viewed', 'Apartment Viewed'), ('apartment_favorited', 'Apartment Favorited'), ('apartment_unfavorited', 'Apartment Unfavorited'), ('building_viewed', 'Building Viewed'), ('property_search', 'Property Search'), ('virtual_tour', 'Virtual Tour Viewed'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent'), ('phone_call', 'Phone Call'), ('message_received', 'Message Received'), ('message_replied', 'Message Replied'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('crm_note_added', 'CRM Note Added'), ('status_changed', 'Status Changed'), ('broker_assigned', 'Broker Assigned'), ('follow_up_scheduled', 'Follow-up Scheduled'), ('meeting_scheduled', 'Meeting Scheduled'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('form_started', 'Form Started'), ('form_abandoned', 'Form Abandoned')], max_length=30),
        ),
    ]
