# Generated by Django 5.1.6 on 2025-11-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0024_alter_applicant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='currently_employed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='open_to_roommates',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='placement_status',
            field=models.CharField(blank=True, choices=[('unplaced', 'Unplaced'), ('placed', 'Placed'), ('withdrawn', 'Withdrawn')], max_length=20, null=True),
        ),
    ]
