# Generated by Django 5.1.6 on 2025-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0025_alter_applicant_currently_employed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousaddress',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent at this previous address', max_digits=10, null=True),
        ),
    ]
