# Generated by Django 5.1.6 on 2025-11-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0026_previousaddress_monthly_rent'),
        ('applications', '0014_application_is_revoked_application_revocation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantactivity',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Related application for this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='applications.application'),
        ),
    ]
