# Generated by Django 5.1.6 on 2025-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0027_applicantactivity_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(db_column='first_name', default='John', max_length=100),
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(db_column='last_name', default='Doe', max_length=100),
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='email',
            new_name='_email',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(blank=True, db_column='phone_number', max_length=20, null=True),
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='phone_number',
            new_name='_phone_number',
        ),
    ]
