# Generated by Django 5.1.6 on 2025-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0028_alter_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='_email',
            field=models.EmailField(db_column='email', default='john@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='_phone_number',
            field=models.CharField(db_column='phone_number', default='555-555-5555', max_length=20),
        ),
    ]
