# Generated by Django 5.1.6 on 2025-12-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0029_alter_applicant__email_alter_applicant__phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousaddress',
            name='months',
            field=models.IntegerField(blank=True, help_text='Months at this address', null=True),
        ),
        migrations.AddField(
            model_name='previousaddress',
            name='years',
            field=models.IntegerField(blank=True, help_text='Years at this address', null=True),
        ),
    ]
