# Generated by Django 5.1.6 on 2026-01-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_add_search_features'),
        ('applicants', '0030_previousaddress_months_previousaddress_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='apartments.apartment')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_apartments', to='applicants.applicant')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('applicant', 'apartment')},
            },
        ),
    ]
