# Generated by Django 5.1.6 on 2026-01-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0031_savedapartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='has_pets',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
