# Generated by Django 5.1.6 on 2026-04-04 20:54
# Modified: Use IF NOT EXISTS guards so this migration is idempotent and safe
# to run on databases where the columns were already added outside of Django.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0032_applicant_has_pets'),
    ]

    operations = [
        # Use raw SQL with IF NOT EXISTS so this is safe even if columns already exist
        migrations.RunSQL(
            sql="ALTER TABLE applicants_applicant ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100) NULL;",
            reverse_sql="ALTER TABLE applicants_applicant DROP COLUMN IF EXISTS middle_name;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE applicants_applicant ADD COLUMN IF NOT EXISTS suffix VARCHAR(20) NULL;",
            reverse_sql="ALTER TABLE applicants_applicant DROP COLUMN IF EXISTS suffix;",
        ),
        migrations.AlterField(
            model_name='applicant',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10, null=True),
        ),
    ]
