# Generated by Django 5.1.6 on 2026-04-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0032_applicant_has_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10, null=True),
        ),
    ]
