# Generated by Django 5.1.6 on 2026-04-04 20:54
# Modified: Use SeparateDatabaseAndState so Django tracks the fields in state
# (stopping makemigrations warnings) while DB ops use IF NOT EXISTS for safety
# on production where columns were already added outside of Django.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0032_applicant_has_pets'),
    ]

    operations = [
        # SeparateDatabaseAndState: state_operations update Django's internal model
        # registry; database_operations use IF NOT EXISTS so it's safe to run even
        # if these columns already exist in production.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='applicant',
                    name='middle_name',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='applicant',
                    name='suffix',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE applicants_applicant ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100) NULL;",
                    reverse_sql="ALTER TABLE applicants_applicant DROP COLUMN IF EXISTS middle_name;",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE applicants_applicant ADD COLUMN IF NOT EXISTS suffix VARCHAR(20) NULL;",
                    reverse_sql="ALTER TABLE applicants_applicant DROP COLUMN IF EXISTS suffix;",
                ),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='previousaddress',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=10, null=True),
        ),
    ]

