# Generated by Django 5.1.6 on 2026-04-04 20:54

from django.db import migrations


def standardize_housing_status(apps, schema_editor):
    """Convert existing lowercase housing_status values to title case."""
    Applicant = apps.get_model('applicants', 'Applicant')
    PreviousAddress = apps.get_model('applicants', 'PreviousAddress')

    # Update Applicant records
    Applicant.objects.filter(housing_status='rent').update(housing_status='Rent')
    Applicant.objects.filter(housing_status='own').update(housing_status='Own')

    # Update PreviousAddress records
    PreviousAddress.objects.filter(housing_status='rent').update(housing_status='Rent')
    PreviousAddress.objects.filter(housing_status='own').update(housing_status='Own')


def reverse_housing_status(apps, schema_editor):
    """Reverse: convert title case back to lowercase."""
    Applicant = apps.get_model('applicants', 'Applicant')
    PreviousAddress = apps.get_model('applicants', 'PreviousAddress')

    Applicant.objects.filter(housing_status='Rent').update(housing_status='rent')
    Applicant.objects.filter(housing_status='Own').update(housing_status='own')

    PreviousAddress.objects.filter(housing_status='Rent').update(housing_status='rent')
    PreviousAddress.objects.filter(housing_status='Own').update(housing_status='own')


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0033_applicant_middle_name_applicant_suffix_and_more'),
    ]

    operations = [
        migrations.RunPython(standardize_housing_status, reverse_housing_status),
    ]
