# Generated by Django 5.1.6 on 2025-11-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_analysis', '0002_alter_documentembedding_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentembedding',
            options={'permissions': [('can_analyze_documents', 'Can analyze uploaded documents')]},
        ),
    ]
