# Generated by Django 5.1.6 on 2025-03-06 21:37

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_address_1', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NY', max_length=2)),
                ('zip_code', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(blank=True, choices=[('Astoria', 'Astoria'), ('Bedford-Stuyvesant', 'Bedford-Stuyvesant'), ('Boerum Hill', 'Boerum Hill'), ('Borough Park', 'Borough Park'), ('Broadway Triangle', 'Broadway Triangle'), ('Brookville', 'Brookville'), ('Brownsville', 'Brownsville'), ('Bushwick', 'Bushwick'), ('Canarsie', 'Canarsie'), ('Carroll Gardens', 'Carroll Gardens'), ('Central Harlem', 'Central Harlem'), ('Chelsea', 'Chelsea'), ('City Line', 'City Line'), ('Clinton Hill', 'Clinton Hill'), ('Cobble Hill', 'Cobble Hill'), ('Columbia Street Waterfront District', 'Columbia Street Waterfront District'), ('Crown Heights', 'Crown Heights'), ('Ditmas Park', 'Ditmas Park'), ('Downtown Brooklyn', 'Downtown Brooklyn'), ('East Flatbush', 'East Flatbush'), ('East Harlem', 'East Harlem'), ('East New York', 'East New York'), ('East Village', 'East Village'), ('East Williamsburg', 'East Williamsburg'), ('Farragut', 'Farragut'), ('Flatbush', 'Flatbush'), ('Flushing', 'Flushing'), ('Fort Greene', 'Fort Greene'), ('Gowanus', 'Gowanus'), ('Gravesend', 'Gravesend'), ('Greenpoint', 'Greenpoint'), ('Greenwood', 'Greenwood'), ('Hamilton Heights', 'Hamilton Heights'), ('Kensington', 'Kensington'), ('Lenox Hill', 'Lenox Hill'), ('Long Island City', 'Long Island City'), ('Marine Park', 'Marine Park'), ('Maspeth', 'Maspeth'), ('Midtown South', 'Midtown South'), ('Midwood', 'Midwood'), ('Mott Haven', 'Mott Haven'), ('Ocean Hill', 'Ocean Hill'), ('Park Slope', 'Park Slope'), ('Prospect Heights', 'Prospect Heights'), ('Prospect Lefferts Gardens', 'Prospect Lefferts Gardens'), ('Red Hook', 'Red Hook'), ('Ridgewood', 'Ridgewood'), ('Sheepshead Bay', 'Sheepshead Bay'), ('Southside', 'Southside'), ('Stuyvesant Heights', 'Stuyvesant Heights'), ('Sunset Park', 'Sunset Park'), ('Turtle Bay', 'Turtle Bay'), ('Vinegar Hill', 'Vinegar Hill'), ('Weeksville', 'Weeksville'), ('Williamsburg', 'Williamsburg'), ('Wingate', 'Wingate'), ('Yorkville', 'Yorkville')], max_length=100, null=True)),
                ('credit_screening_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_screening_payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('ach', 'ACH'), ('check', 'Deliver Check'), ('zelle', 'Zelle'), ('venmo', 'Venmo')], max_length=20, null=True)),
                ('hold_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hold_deposit_payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('ach', 'ACH'), ('check', 'Deliver Check'), ('zelle', 'Zelle'), ('venmo', 'Venmo')], max_length=20, null=True)),
                ('pet_policy', models.CharField(blank=True, choices=[('case_by_case', 'Case by Case'), ('pet_fee', 'Pet Fee'), ('all_pets', 'All pets allowed'), ('small_pets', 'Small pets allowed'), ('cats_only', 'Cats only'), ('no_pets', 'No pets')], max_length=20, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_pay_type', models.CharField(blank=True, choices=[('owner_pays', 'Owner Pays'), ('tenant_pays', 'Tenant Pays'), ('owner_and_tenant_pays', 'Owner and Tenant Pays')], max_length=25, null=True)),
                ('commission_owner_months', models.IntegerField(blank=True, null=True)),
                ('commission_tenant_months', models.IntegerField(blank=True, null=True)),
                ('commission_owner_percent', models.IntegerField(blank=True, null=True)),
                ('commission_tenant_percent', models.IntegerField(blank=True, null=True)),
                ('commission_takeoff_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internal_notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='buildings.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('time_restriction_enabled', models.BooleanField(default=False)),
                ('access_type', models.CharField(blank=True, choices=[('pin', 'Pin Code'), ('note', 'Note')], max_length=10, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('custom_note', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_points', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_type', models.CharField(blank=True, choices=[('concession', 'Concession'), ('free_stuff', 'Free Stuff')], max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('months_free', models.IntegerField(blank=True, null=True)),
                ('lease_terms', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('free_stuff_items', models.CharField(blank=True, max_length=255, null=True)),
                ('is_time_based', models.BooleanField(default=False)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('trigger_event', models.CharField(blank=True, choices=[('application_submitted', 'Application Submitted'), ('lease_signed', 'Lease Signed'), ('move_in', 'Move In')], max_length=25, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='buildings.building')),
            ],
        ),
    ]
