# Generated by Django 5.1.6 on 2025-12-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_add_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bike_description',
            field=models.CharField(blank=True, help_text='Text description of bikeability', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='bike_score',
            field=models.IntegerField(blank=True, help_text='Bike Score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='neighborhood_data_updated',
            field=models.DateTimeField(blank=True, help_text='Last time API data was updated', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='transit_description',
            field=models.CharField(blank=True, help_text='Text description of transit access', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='transit_score',
            field=models.IntegerField(blank=True, help_text='Transit Score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='walk_description',
            field=models.CharField(blank=True, help_text='Text description of walkability', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='walk_score',
            field=models.IntegerField(blank=True, help_text='Walk Score (0-100)', null=True),
        ),
        migrations.CreateModel(
            name='NearbySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, help_text='GreatSchools rating (1-10)', null=True)),
                ('grades', models.CharField(blank=True, help_text="e.g. 'PK-5' or '9-12'", max_length=100, null=True)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in miles', max_digits=4)),
                ('school_type', models.CharField(blank=True, help_text="e.g. 'Public', 'Private', 'Charter'", max_length=50, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_schools', to='buildings.building')),
            ],
            options={
                'ordering': ['distance'],
                'unique_together': {('building', 'name')},
            },
        ),
    ]
