# Generated by Django 5.1.6 on 2026-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_building_bike_description_building_bike_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(default='fa-check-circle', help_text="FontAwesome icon class (e.g. 'fa-swimming-pool')", max_length=50),
        ),
    ]
