# Generated by Django 5.1.6 on 2026-01-02 13:24

from django.db import migrations

def populate_amenity_icons(apps, schema_editor):
    Amenity = apps.get_model('buildings', 'Amenity')
    
    # Mapping of amenity names to FontAwesome icon classes
    icon_mapping = {
        'Bike Room': 'fa-bicycle',
        'Business center': 'fa-briefcase',
        "Children's Play Room": 'fa-child-reaching',
        'Cold Storage': 'fa-snowflake',
        'Concierge': 'fa-bell-concierge',
        'Courtyard': 'fa-tree',
        'Covered parking': 'fa-square-parking',
        'Doorman': 'fa-user-tie',
        'Elevator': 'fa-elevator',
        'Fitness Center': 'fa-dumbbell',
        'Garage Parking': 'fa-warehouse',
        'Garbage chute': 'fa-trash-can',
        'Garden': 'fa-leaf',
        'Green building': 'fa-seedling',
        'Guarantors Welcome': 'fa-file-signature',
        'Gym': 'fa-dumbbell',
        'Laundry': 'fa-jug-detergent',
        'Laundry In Building': 'fa-jug-detergent',
        'Live In Super': 'fa-user-gear',
        'On site super': 'fa-user-gear',
        'Locker Rooms': 'fa-door-closed',
        'Media Room': 'fa-film',
        'Non Smoking Building': 'fa-ban-smoking',
        'Smoke free property': 'fa-ban-smoking',
        'Outdoor Spaces': 'fa-sun',
        'Package Room': 'fa-box-open',
        'Parking': 'fa-square-parking',
        'Pet spa': 'fa-paw',
        'Pool': 'fa-water-ladder',
        'Recreation': 'fa-table-tennis-paddle-ball',
        'Resident Lounge': 'fa-couch',
        'Roof Access': 'fa-umbrella-beach',
        'Roof Deck': 'fa-umbrella-beach',
        'Screening room': 'fa-video',
        'Security cameras': 'fa-video',
        'Storage': 'fa-boxes-stacked',
        'Valet': 'fa-car-side',
        'Verizon Fios': 'fa-wifi',
        'Virtual Doorman': 'fa-robot',
        'Wheelchair Access': 'fa-wheelchair',
        'Yoga studio': 'fa-spa',
    }

    count = 0
    for name, icon in icon_mapping.items():
        # Update matching amenities (case-insensitive if possible, but exact match for now based on list)
        updated = Amenity.objects.filter(name__iexact=name).update(icon=icon)
        count += updated
    
    print(f"\nUpdated {count} building amenities with icons.")

def reverse_amenity_icons(apps, schema_editor):
    Amenity = apps.get_model('buildings', 'Amenity')
    Amenity.objects.all().update(icon='fa-check-circle')

class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_amenity_icon'),
    ]

    operations = [
        migrations.RunPython(populate_amenity_icons, reverse_amenity_icons),
    ]
